### ISSUE TITLE
No emails triggers error

### ISSUE THREAD

**Issue by flightltd** [benhall14/php-imap-reader#10]
This occurs when the email object has no entries:

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/developerbootcamp.co.uk/admin.developerbootcamp.co.uk/libs/php/phpImapReader/Reader.php on line 802

**Comment by cljorgensen** [comment]
Yes it does:

Is this a valid fix?

  if($this->email_index != 0){
      if (!$this->limit) {
          $this->limit = count($this->email_index);
      }
  }
  
  else{
      $this->limit = 0;
  }

**Comment by benhall14** [comment]
This should now be fixed.

**Comment by itcareerswitch** [comment]
Thanks - I'll try it when I get a moment and get back.
