### ISSUE TITLE
Problem with get all attachments and display images inside mail 

### ISSUE THREAD

**Issue by rafaliex** [benhall14/php-imap-reader#12]
Hi, I use your class from few days and I saw a little problem.

I have mail with 4 .html attachments and two images inside message.

And When I list attachments throught your class is showing me only 3 attachements but inside are two gifs (images from message) and one html file.

When I use method html message is empty but when i get plain is getting message but without that images.

I got another mail but with 4 .xls files and 2 images inside message and its the same problem in attachments are only two images and one xls file.

And second it is possible to detect encoding of attachments? Because I saw that in mails for each attachment it could be different encoding and from time to time when class save attachments theirs names are wrong.

**Comment by benhall14** [comment]
Thanks for picking this up. I've added (and tested) a fix for this which should solve your problem.

Thanks,
Ben
