### ISSUE TITLE
Mark as read issue

### ISSUE THREAD

**Issue by mertuarez** [benhall14/php-imap-reader#15]
https://github.com/benhall14/php-imap-reader/blob/ba7bca02afb71b20d962b17238db17baa3169530/src/phpImapReader/Reader.php#L962

This should not also mark as read
 $email->setRawBody(imap_fetchbody($this->stream(), $uid, '', **FT_UID | FT_PEEK**));

 So has to follow flags
 $email->setRawBody(imap_fetchbody($this->stream(), $uid, '', **$options**));

**Comment by benhall14** [comment]
Good catch - I've updated the code now to respect the $options set.

Thanks,
Ben
