### ISSUE TITLE
Base64 Decode

### ISSUE THREAD

**Issue by DiemenDesign** [benhall14/php-imap-reader#2]
Hi, thanks for a great little imap parser, I'm using it in my LibreCMS project in my webmail part of the CMS. However, I've discovered some emails that are received have the body encoded with a base64 encoding.

I've had a look through your source, and it looks as though you have an imap_base64 in the receiving part of the script. Should it be decrypting base64 or base8 decryped emails? I tried to check if you have a check to do so, but couldn't find it. I could easily store a flag in my database to indicate the type of encoding, but I need to be able to tell which meissages are encoded, and which aren't.

Again, thanks for making the script, it's easy to use, and works great for my purposes.

**Comment by DiemenDesign** [comment]
I found this, which might be helpful for others look for old issues for the same problem.
````php
function is_base64_string($s) {
  if (($b = base64_decode($s, TRUE)) === FALSE) {
    return FALSE;
  }
  $e = mb_detect_encoding($b);
  if (in_array($e, array('UTF-8', 'ASCII'))) { // YMMV
    return TRUE;
  } else {
    return FALSE;
  }
}
````

**Comment by truefriend-cz** [comment]
> I found this, which might be helpful for others look for old issues for the same problem.
> 
> ```
> function is_base64_string($s) {
>   if (($b = base64_decode($s, TRUE)) === FALSE) {
>     return FALSE;
>   }
>   $e = mb_detect_encoding($b);
>   if (in_array($e, array('UTF-8', 'ASCII'))) { // YMMV
>     return TRUE;
>   } else {
>     return FALSE;
>   }
> }
> ```

Do you can help me...
I dont know where adding your code to scripts.
Can you write what line number and what file should I add this code to and what else do I need to edit?

**Comment by DiemenDesign** [comment]
It's just a PHP function, you can add it anywhere where your script can access it. It's seperate from the project code.
