### ISSUE TITLE
Create Mailbox?

### ISSUE THREAD

**Issue by SoftCreatR** [benhall14/php-imap-reader#20]
Hi,

it would be great, if this class would also support creating new mailboxes/folders via `imap_createmailbox`. Maybe including the possibility to determine, if the given mailbox/folder already exists.

**Comment by benhall14** [comment]
Great suggestion - I've added this in now :)

->doesFolderExist('Folder Name') - returns true/false based on if the mailbox is found on the IMAP stream.
->createFolder('New Folder Name') - creates a new folder, if it doesn't already exist on the IMAP stream.

Thanks,
Ben

**Comment by SoftCreatR** [comment]
Neat. Thank you :) I'll try it later this day.
