### ISSUE TITLE
Filter by custom header

### ISSUE THREAD

**Issue by itajackass** [benhall14/php-imap-reader#22]
Hi, is there any function to filters email by custom header? For example "References" key or any other custom ones? thanks

**Comment by benhall14** [comment]
There isn't any functionality to filter by header directly, but you should be able to use the searchText() method. For example, ->searchText('X-Priority: 3') should only return emails that have an X-Priority header set to 3.

You can get the custom headers on the Email using getHeader();

Thanks,
Ben

**Comment by benhall14** [comment]
As far as I'm aware, you can't use wildcards on the search. In that case, the only way I can think of would be to fetch all emails and then search the headers in each message to filter down afterwards.

Thanks,
Ben
