### ISSUE TITLE
Error during retrieve attachment

### ISSUE THREAD

**Issue by itajackass** [benhall14/php-imap-reader#23]
Hi, i'm trying to retrieve content data of an attachment with: $attachment->content(); but i get this error:

    Warning: Undefined property: benhall14\phpImapReader\EmailAttachment::$attachment_data  ...... on line 173

if I print a var_dump i get my attachment like this:

    object(benhall14\phpImapReader\EmailAttachment)[24]
      public 'id' => int 738572691
      public 'name' => string 'logo.png'
      public 'file_path' => null
      public 'type' => string 'attachment' (length=10)
      public 'mime' => null

I've set:

    define('ATTACHMENT_PATH', false);

If I set:

     define('ATTACHMENT_PATH', __DIR__ . '/attachments');

I get ALL attachments to be downloaded (of all emails). My goal is to download attachments only for a specific email, searching inside the header (like my past ticket closed)... but to do my search I need to download ALL emails, then filter trought header...

Any suggest? thanks

**Comment by benhall14** [comment]
Good catch on this - I've added a fix and pushed a release.

Thanks,
Ben
