### ISSUE TITLE
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated

### ISSUE THREAD

**Issue by iThom96** [benhall14/php-imap-reader#26]
When using `$email->html()` i get a warning:

```
( ! ) Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array\|string is deprecated in /vendor/benhall14/php-imap-reader/src/phpImapReader/Email.php on line 836
```

**Comment by benhall14** [comment]
Thanks for letting me know.

I've added a fix now - basically, the filePath() was returning null (for whatever reason). The updated version will check the id and filepath before calling str_replace.
