### ISSUE TITLE
Unable to get attachment files when no attachment folder is set

### ISSUE THREAD

**Issue by GWidman** [benhall14/php-imap-reader#27]
Hi,
  I'm using phpImapReader to pull in attached files from an email account.  I wasn't able to get the EmailAttachment->contents to work.
  It looks like the issue is in line 1237 of the Reader.php file.  
`$attachment->setAttachmentContent($data)` is commented out.  

  I replaced it with:

$attachement->setAttachmentData($data)

  That seems to work.

  Regards,
  Greg

**Comment by benhall14** [comment]
I believe there was an issue with large attachment data being set on the fly, when a local directory for storage wasn't set. I've reverted the comment now to allow you to handle attachment data on the fly again.

Thanks,
Ben
