### ISSUE TITLE
Fatal error: Uncaught ErrorException: Creation of dynamic property benhall14\phpImapReader\Reader::$encoding is deprecated in /var/www/html/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php on line 145

### ISSUE THREAD

**Issue by ciberstrigo** [benhall14/php-imap-reader#28]
Fatal error: Uncaught ErrorException: Creation of dynamic property benhall14\phpImapReader\Reader::$encoding is deprecated in /var/www/html/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php on line 145

Tried to create Reader instance like this:

```
use benhall14\phpImapReader\Reader;

$imap = new Reader(
    $_ENV['IMAP_SERVER'],
    $_ENV['IMAP_LOGIN'],
    $_ENV['IMAP_PASSWORD'],
    mark_as_read: false
);
```

And as I see, there really is no $encoding field in the Reader class. Fix it please.

**Comment by benhall14** [comment]
Thanks for catching this bug - I've updated it now.

Thanks,
Ben
