### ISSUE TITLE
reset function does not exist

### ISSUE THREAD

**Issue by Joosep254** [benhall14/php-imap-reader#29]
It works almost perfectly, no issues so far. But from now on i need to change the mailbox and i read from the docs that i should use the reset function but it does not exist...

**Comment by benhall14** [comment]
You should be able to access it like this:

$imap->reset()->folder('Sent')->get();

This will reset the folder and connect to the 'sent' folder.

**Comment by Joosep254** [comment]
Thank you for your input. I now have another issue, i updated the code (i had previous version) and now i have an error:
Fatal error: Uncaught Error: Call to undefined method benhall14\phpImapReader\EmailAttachment::setAttachmentContent()
(Reader.php line 1258) but class EmailAttachment does not have such method...

**Comment by benhall14** [comment]
This should be fixed now.
