### ISSUE TITLE
mb_convert_encoding PHP8.1

### ISSUE THREAD

**Issue by LloydSims** [benhall14/php-imap-reader#31]
Works fine with PHP7.0, but 8.1 gave me the following error from
`$imap->limit(3)->reset()->folder('INBOX')->get();`

`Fatal error: Uncaught ValueError: mb_convert_encoding(): Argument #2 ($to_encoding) must be a valid encoding, "" given in /home/XXX/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php:1345 
Stack trace: #0 /home/XXX/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php(1345): mb_convert_encoding() #1 /home/XXX/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php(1318): 
benhall14\phpImapReader\Reader->convertEncoding() #2 /home/XXX/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php(1045): 
benhall14\phpImapReader\Reader->decodeMimeHeader() #3 /home/XXX/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php(1005): 
benhall14\phpImapReader\Reader->getEmail() #4 /home/XXX/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php(971): 
benhall14\phpImapReader\Reader->getEmailByMessageSequence() #5 /home/XXX/public_html/YYYs/XXX.php(54): 
benhall14\phpImapReader\Reader->get() #6 /home/XXX/public_html/YYY.php(81): 
include('...') #7 {main} thrown in /home/XXX/vendor/benhall14/php-imap-reader/src/phpImapReader/Reader.php on line 1345`

**Comment by benhall14** [comment]
When you are setting up the reader, are you adding a custom encoding type?

$imap = new Reader(IMAP_MAILBOX, IMAP_USERNAME, IMAP_PASSWORD, ATTACHMENT_PATH, false, 'UTF-8');

By default, it will use UTF-8 as the encoding type. I've tested on PHP 8.3 and I'm not getting that error. The fact that the encoding is "", looks like it's being explicitly set to "".

**Comment by LloydSims** [comment]
Exactly that, thanks. I thought I was defauling it to UTF-8 that way and as it was working on 7.0, I didn't question it.
Apologies for taking your time.

**Comment by benhall14** [comment]
Glad it's fixed for you now :)
