### ISSUE TITLE
Count All Messages in Imap folder

### ISSUE THREAD

**Issue by truefriend-cz** [benhall14/php-imap-reader#4]
Hi. How i get all messages in IMAP folder number?

**Comment by benhall14** [comment]
This is probably a little bit late :) but I'll add the answer anyway, in case it helps someone else.

I think the easiest way would be to get all of the emails in the folder, and then count the resulting emails array.

`
$folder = 'name-of-the-folder';
$imap->folder($folder)->get();
$count = count($imap->emails());
` 

I haven't tested, but something like that should work.

**Comment by mertuarez** [comment]
@truefriend-cz 
$imap = new Reader(...);
$cnt = imap_num_msg($imap-->stream());
