### ISSUE TITLE
Emails always marked as read

### ISSUE THREAD

**Issue by roylanceb** [benhall14/php-imap-reader#8]
I've tried connecting to the mailbox using this:

$imap = new Reader(IMAP_MAILBOX, IMAP_USERNAME, IMAP_PASSWORD, false, false);

And the emails retrieve correctly, but they're always flagged as read.

I've even tried commenting out this section

```
if ($this->mark_as_read) {
	//$this->markAsRead($id);
}
```

And still they're flagged as read.

This is how I'm retrieving the emails:

```
$imap->unseen();
$imap->get();
```

**Comment by benhall14** [comment]
There isn't anything in the code that explicitly sets the 'read' flag. If you choose to set the 'mark as read' to false when instantiating a Reader, the class will honour the FT_PEEK when fetching the email - i.e fetch the email and do not set the 'seen' flag if it's not already set, but that depends on the IMAP server.

I've added a fix where the FT_PEEK was missing from the getEmail method, which may or may not fix the issue. Please retry using the v1.2.

In my local tests with a few different IMAP sources, the emails aren't marked as seen unless you explicitly mark the email as read.

**Comment by roylanceb** [comment]
That looks to have worked, thanks!

I've made a few other changes due to some small bugs I ran into. Should I open issues for those too? Or create a pull request?

**Comment by benhall14** [comment]
That's great!

Create a pull request with the changes and I'll take a look asap.

**Comment by mertuarez** [comment]
Fixed.
